clear
vocab
' vocab disasm


: ?DUP DUP IF DUP THEN ;
: ?DROP DUP IF DROP THEN ;
: ?NIP DUP IF NIP THEN ;
: ?LEAVE IF R> DROP LEAVE THEN ;

: KEY? KEY DUP ISSPACE ?NIP ;






: APPEND ( char addr -- )
    TUCK COUNT + ! ++
;
: READ ( addr n -- )
  OVER 0 SWAP !
  DUP 0 <=
  IF DROP DROP EXIT THEN
  BEGIN KEY? 0= UNTIL
  2 PICK APPEND
  1 DO
    KEY? ?LEAVE
    OVER APPEND
  LOOP DROP
;
: FIND ( addr -- addr 0 | xt 1 | xt -1 )
  LAST BEGIN DUP 0<> WHILE
    DUP NAME 2 PICK COUNT STREQ
    IF NIP DUP CODE SWAP FLAGS IMM? IF 1 ELSE -1 THEN EXIT THEN
  PREV REPEAT
;

HERE 256 ALLOT
CONSTANT TIB

: WORD TIB 31 READ TIB ;


: ' WORD FIND 0= IF DROP 0 THEN ;
: ['] ' POSTPONE LITERAL ; IMMEDIATE
: POSTPONE
  WORD FIND
  DUP  0 = IF DROP DROP EXIT THEN
  DUP  1 = IF DROP POSTPONE [POSTPONEI] COMPILE, EXIT THEN
  DUP -1 = IF DROP POSTPONE [POSTPONE] COMPILE, EXIT THEN
  DROP DROP
; IMMEDIATE
(
: POSTPONE
  WORD FIND
  DUP  0 = IF DROP DROP EXIT THEN
  DUP  1 = IF DROP COMPILE, EXIT THEN
  DUP -1 = IF DROP POSTPONE LITERAL POSTPONE COMPILE, EXIT THEN
  DROP DROP
; IMMEDIATE
)

(
: ?? POSTPONE DUP
     POSTPONE IF
     POSTPONE ['] POSTPONE EXECUTE
     POSTPONE THEN
; IMMEDIATE
)


: SOURCE TIB COUNT ;


: X
  DUP  1 = IF DROP EXECUTE EXIT THEN
  DUP -1 = IF DROP COMPILE, EXIT THEN
  DUP  0 = IF 123 POSTPONE LITERAL EXIT THEN
;
: ; visible state off ; IMMEDIATE
: :
  STATE ON
  BEGIN STATE @ WHILE
    WORD FIND X
  REPEAT
;



: MODULE POSTPONE VARIABLE IMMEDIATE ;


\ CLIB :: STRING :: STRLEN

: SEARCH ( addr1 addr2 -- addr 0 | xt 1 | xt -1 )
  BEGIN DUP 0<> WHILE
    DUP NAME 2 PICK COUNT STREQ
    IF NIP DUP CODE SWAP FLAGS IMM? IF 1 ELSE -1 THEN EXIT THEN
  PREV REPEAT
;
: X
  DUP  0 = IF DROP DROP EXIT THEN
  DUP  1 = IF DROP EXECUTE EXIT THEN
  DUP -1 = IF DROP STATE @ IF COMPILE, ELSE EXECUTE THEN EXIT THEN
  DROP DROP
;

: WORD TIB 31 READ TIB ;

: :: WORD SWAP @ SEARCH X ; IMMEDIATE
\ WILL probably also need
\ :' :POSTPONE ...
\ CLIB :: CLASS1 :POSTPONE asdf

VARIABLE X

\ LAST :: X

CLIB :: STRING DICT
\ Then everything belongs to that dict


VARIABLE DICT
: MODULE CREATE 0 , 0 , IMMEDIATE ;
: :: @ WORD SWAP SEARCH X ; IMMEDIATE
: OPEN-DICT
  DICT @ OVER CELL+ !
  DICT !
;















\ clear

